import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "../styles/variables.css";
import MainNavigation from "@/components/Header";
import Footer from "@/components/Footer";
import "./not-found";
import ContactModal from "@/components/modals/ContactModal";
import CookiesPopup from "@/common-components/cookies/cookies";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "https://res.cloudinary.com/djxgpbncu/image/upload/v1768288792/logo-4_p2iwwi.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          strategy="beforeInteractive"
          src="https://t.contentsquare.net/uxa/d252099aa0f2e.js"
        ></Script>
        <Script
          strategy="beforeInteractive"
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-DBTW8G5KT3"
        />
        <Script id="google-analytics" strategy="beforeInteractive">
          {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-DBTW8G5KT3')`}
        </Script>

        <Script id="googletagmanager" strategy="beforeInteractive">
          {`
           <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-MKKPGJ72');</script>`}
        </Script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainNavigation />
        {children}
        <Footer />
        <ContactModal />
        <CookiesPopup />
      </body>
    </html>
  );
}
