import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "../styles/variables.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "https://pub-ec3822a2d8d6482db36eb9dadc028ea6.r2.dev/logo/madhuban-eco-retreat-bhopal-logo.png",
  },
};

// Chrome-free on purpose: this layout owns only <html>/<body>, fonts, global CSS
// and site-wide analytics. The marketing header/footer/modals live in
// (marketing)/layout.js so /book and /admin do not inherit them. Analytics stays
// here deliberately — the booking funnel is exactly where conversion tracking
// has to keep firing.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          strategy="afterInteractive"
          src="https://t.contentsquare.net/uxa/d252099aa0f2e.js"
        ></Script>
        <Script
          strategy="afterInteractive"
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-DBTW8G5KT3"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-DBTW8G5KT3')`}
        </Script>

        <Script id="googletagmanager" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-MKKPGJ72');`}
        </Script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <noscript
          dangerouslySetInnerHTML={{
            __html: `
      <iframe
        src="https://www.googletagmanager.com/ns.html?id=GTM-MKKPGJ72"
        height="0"
        width="0"
        style="display:none;visibility:hidden"
      ></iframe>
    `,
          }}
        />

        {children}
      </body>
    </html>
  );
}
